/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evideostb_training_chenhuan_mytest01service */

#ifndef _Included_com_evideostb_training_chenhuan_mytest01service
#define _Included_com_evideostb_training_chenhuan_mytest01service
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evideostb_training_chenhuan_MyTest01Activity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_evideostb_training_chenhuan_mytest01service_MyTest01Service_getStringFromNative
  (JNIEnv *, jobject);

JNIEXPORT jobject JNICALL Java_com_evideostb_training_chenhuan_mytest01service_SerialPort_open
  (JNIEnv *env, jobject thiz, jstring path,jint baudrate);

JNIEXPORT jint JNICALL Java_com_evideostb_training_chenhuan_mytest01service_SerialPort_close
  (JNIEnv * env, jobject thiz);
#ifdef __cplusplus
}
#endif
#endif
